<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>disable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Haruka.Arcade.Apm.GameGuideEditor</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Update="Preview.cs">
            <SubType>Form</SubType>
        </Compile>
        <Compile Update="Settings.cs">
            <SubType>Form</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    </ItemGroup>

</Project>