<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net481</TargetFramework>
        <AssemblyName>BananaphoneEmoneyUi</AssemblyName>
        <Product>BananaphoneEmoneyUi</Product>
        <Version>1.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Haruka.Arcade.Apm.Bananaphone.Emui</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>..\Libs\bepinex\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="AMDaemon.NET">
            <HintPath>..\Libs\apm\AMDaemon.NET.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>..\Libs\emui\Assembly-CSharp-nstrip.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx">
            <HintPath>..\Libs\bepinex\BepInEx.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.Harmony">
            <HintPath>..\Libs\bepinex\BepInEx.Harmony.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>..\Libs\apm\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\Libs\apm\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>..\Libs\apm\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>..\Libs\apm\UnityEngine.UIModule.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BananaphoneLib\BananaphoneLib.csproj"/>
    </ItemGroup>
</Project>
