<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>Haruka.Arcade.EXMoney</RootNamespace>
        <AssemblyVersion>1.0</AssemblyVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1"/>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="NReco.Logging.File" Version="1.4.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SEGA835Lib\SEGA835Lib\SEGA835Lib.csproj"/>
        <ProjectReference Include="..\..\SegApiCS\SegApiCS\SegApiCS.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="exmoney.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="exmoney.debug.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Target Name="SetHash" AfterTargets="InitializeSourceControlInformation">

        <Exec Command="git.exe describe --always --dirty --exclude='*' --abbrev=8" ConsoleToMSBuild="True" IgnoreExitCode="False">
            <Output PropertyName="Revision" TaskParameter="ConsoleOutput"/>
        </Exec>

        <ItemGroup>
            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>GitHash</_Parameter1>
                <_Parameter2>$(Revision)</_Parameter2>
            </AssemblyAttribute>
        </ItemGroup>

    </Target>

</Project>
